# Change these first
owner: yangxinlei # Your GitHub username
repo: yzh_monitor # Your GitHub repository name

# Add your sites here
sites:
  - name: yzh
    url: http://www.yzhjp.cn
    
status-website:
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /yzh_monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: yzh page monitor
  introTitle: "nil"
  introMessage: nil
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
